### Step1
##### install numpy 

In [2]:
#!pip install numpy

### Step2
##### import numpy

In [3]:
import numpy as np

In [50]:
# Create numpy array ID with elements from 1 to 20
ID = np.arange(1, 21)
ID

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

###### 1(a). Cal. sum, mean, median and std

In [8]:
print(f'Sum of all elements are: {np.sum(ID)}')
print(f'Mean of array: {np.mean(ID)}')
print(f'Median of array: {np.median(ID)}')
print(f'Standard deviation of array(ID): {np.std(ID)}')

Sum of all elements are: 210
Mean of array: 10.5
Median of array: 10.5
Standard deviation of array(ID): 5.766281297335398


###### 1(b). Find the indices of elements greater than 10

In [51]:
idx = np.where(ID > 10) # return index of each element which is greater than 10
print(idx)

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


###### 2(a) Create 2d array of shape 4*4

In [23]:
arr = np.arange(1, 17).reshape(4, 4)
print('2D Array of shape(4*4)\n', arr)

2D Array of shape(4*4)
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


###### 2(b) find transpose of array

In [27]:
print('Transpose of array is:\n', np.transpose(arr))

Transpose of array is:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


###### 2(c) cal. row-wise and column-wise sum 

In [28]:
print(f'sum of elements for each row: {np.sum(arr, axis = 1)}')
print(f'sum of elements for each column: {np.sum(arr, axis = 0)}')

sum of elements for each row: [10 26 42 58]
sum of elements for each column: [28 32 36 40]


###### 3(a) create 2 Array (3*3) with random numbers from 1 to 16. And perform elements-wise addition, sub, and multiplication

In [32]:
arr1 = np.random.randint(1, 16, (3, 3))
arr2 = np.random.randint(1, 16, (3, 3))
print(arr1)
print(arr2)

[[15 13  5]
 [ 1  4  3]
 [ 6 10  6]]
[[10 15 12]
 [ 7 12 11]
 [ 6 14 15]]


In [33]:
print('Addition:\n', arr1+arr2)
print('Subtraction:\n', arr1-arr2)
print('Multiplication:\n', arr1*arr2)

Addition:
 [[25 28 17]
 [ 8 16 14]
 [12 24 21]]
Subtraction:
 [[ 5 -2 -7]
 [-6 -8 -8]
 [ 0 -4 -9]]
Multiplication:
 [[150 195  60]
 [  7  48  33]
 [ 36 140  90]]


###### 3(b) compute the dot product of the arrays

In [35]:
print(np.dot(arr1 ,arr2))

[[271 451 398]
 [ 56 105 101]
 [166 294 272]]


###### 4. Reshape a ID array ofsize 12 into a 3*4 2d array and slice the first two rows and last two columns

In [39]:
ID = np.arange(1, 13).reshape(3, 4)
ID

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
print('First two rows:\n', ID[0:2])
print('Last column:\n', ID[:, 3])

First two rows:
 [[1 2 3 4]
 [5 6 7 8]]
Last column:
 [ 4  8 12]
