### array : data structure in numpy

In [3]:
import numpy as np

In [4]:
# 1D array
arr1 = np.array([1, 2, 3])
print(arr1)
print(type(arr1))
print(type([1, 2, 3]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'list'>


In [5]:
import time
li = list(range(100000000))
arr = np.arange(100000000)
start = time.time()
sum(li)
print(time.time()-start)
start = time.time()
np.sum(arr)
print(time.time()-start)

7.911302328109741
0.4444417953491211


In [7]:
# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [31]:
# array of zeros, ones and range

In [34]:
arr = np.zeros((2, 3)) # 2-rows and 3-columns
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
arrs1 = np.ones((2, 4))
print(arrs1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
ar = np.arange(2, 11, 2)
print(ar)

[ 2  4  6  8 10]


### Array Operations

In [127]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
print(a+b)
print(a**2)
print(a/b)

[3 6 9]
[1 4 9]
[0.5 0.5 0.5]


In [128]:
print(a+4)
print(a)

[5 6 7]
[1 2 3]


In [27]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 2, 3], [4, 5, 6]])
print(x+y)
print(x+10)
print(x*y)

[[ 2  4  6]
 [ 8 10 12]]
[[11 12 13]
 [14 15 16]]
[[ 1  4  9]
 [16 25 36]]


In [11]:
print(x[1, 1])

5


In [55]:
print(x[0, :])

[1 2 3]


In [115]:
print(x[ :,: ])

[[1 2 3]
 [4 5 6]]


In [15]:
print(x[:, -1])

[3 6]


In [17]:
print(x)

[[1 2 3]
 [4 5 6]]


In [28]:
print(x[:,0])

[1 4]


### Reshaping
##### reshape(rows, columns): used to change the dimensions of an array in numpy

In [8]:
#reshaped = np.arange(12).reshape(2, 6)
reshaped = np.arange(12)
reshaped = reshaped.reshape(2, 6)
print(reshaped)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Functions of Numpy

In [42]:
arr = np.array([3, 1, 4, 8, 2, 9, 7])
print(f'Mean: {np.mean(arr)}')

Mean: 4.857142857142857


In [43]:
print(f'Standard Deviations: {round(np.std(arr), 2)}')

Standard Deviations: 2.9


In [44]:
print(np.median(arr))

4.0


In [45]:
print(np.sort(arr))

[1 2 3 4 7 8 9]


In [49]:
# linspace(start, stop, num):
# used to create array in numpy or generates sequence of evenly spaced-values
print(np.linspace(1, 2, 5))
# start: sequence starts value
# stop: sequence stop value and it is include in result
# num: specify samples means interval from 1 to 5 divides, how many parts

[1.   1.25 1.5  1.75 2.  ]


In [87]:
ran = np.random.randint(1, 4, (3, 3))

In [88]:
print(ran)

[[3 3 2]
 [1 3 2]
 [1 3 2]]


In [91]:
nd = np.arange(1, 26).reshape(5, 5)
print(nd)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [92]:
print(nd[1:4, 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [93]:
print(nd[:, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [97]:
print('Row-wise sum: ', np.sum(nd, axis = 1))

Row-wise sum:  [ 15  40  65  90 115]


In [98]:
print('Column-wise sum: ', np.sum(nd, axis = 0))

Column-wise sum:  [55 60 65 70 75]


# CASE STUDY

In [10]:
claims = np.array([[10000, 12000, 15000], # for 1 holders
                  [3000, 9000, 20000],    # 2
                  [90000, 11000, 25000]]) # 3

In [11]:
print(f'Claims done by policy holder 3 in month 2: {claims[2, 1]}')

Claims done by policy holder 3 in month 2: 11000


In [12]:
print('Total claims per holders')
print(np.sum(claims, axis = 1))

Total claims per holders
[ 37000  32000 126000]


In [13]:
# avg claims per month

In [14]:
print('Avg claims per month', np.mean(claims, axis = 0))

Avg claims per month [34333.33333333 10666.66666667 20000.        ]


In [16]:
# claims above 15000
high_claims = claims[claims > 15000]
print(high_claims)

[20000 90000 25000]


# CASE STUDY 2

### Customer feedback analysis in retail industry using numpy

In [112]:
import numpy

In [17]:
data = np.array([['C001', 4, 'Excellent service'],
                ['C002', 5, 'Very good customer support'],
                ['C003', 1, 'Very poor service'],
                ['C004', 2, 'Poor customer support'],
                ['C005', 3, 'Average service'],
                ['C006', 4, 'Discount are good'],
                ['C007', 3, 'Avergae service'],
                ['C008', 4, 'Fast and clean service']])

In [18]:
print(data)
print(type(data))

[['C001' '4' 'Excellent service']
 ['C002' '5' 'Very good customer support']
 ['C003' '1' 'Very poor service']
 ['C004' '2' 'Poor customer support']
 ['C005' '3' 'Average service']
 ['C006' '4' 'Discount are good']
 ['C007' '3' 'Avergae service']
 ['C008' '4' 'Fast and clean service']]
<class 'numpy.ndarray'>


In [19]:
# total feedback
ratings = data[:, 1].astype(int) # convert rating into integers
print(ratings)
print(f'Total ratings are: {len(ratings)}')

[4 5 1 2 3 4 3 4]
Total ratings are: 8


In [123]:
# avg rating
print(f'Average ratings: {np.mean(ratings)}')

Average ratings: 3.25


In [124]:
# highest rating
print(f'Highest rating is: {np.max(ratings)}')

Highest rating is: 5


In [125]:
# minimum ratind
print(f'Minimum rating is: {np.min(ratings)}')

Minimum rating is: 1


In [129]:
unique_rating, rating_counts = np.unique(ratings, return_counts = True)

In [130]:
print(f'Unique ratings: {unique_rating}')
print(f'Rating Counts: {rating_counts}')

Unique ratings: [1 2 3 4 5]
Rating Counts: [1 1 2 3 1]


In [140]:
print('Rating Distributions')
for rating, counts in zip(unique_rating, rating_counts):
#The Python zip() function is a built-in utility that takes one or more iterables (like lists, tuples, or strings) and 
#aggregates their corresponding elements into a single iterator of tuples
    print('Rating ',rating, ': ', counts, ' Customers' )
   # print(rating, counts)

Rating Distributions
Rating  1 :  1  Customers
Rating  2 :  1  Customers
Rating  3 :  2  Customers
Rating  4 :  3  Customers
Rating  5 :  1  Customers


In [142]:
feedback_cust = data[:, 2]
print('Customers feedback analysis')
print()
for feed in feedback_cust[ : 5]:
    print('-', feed)

Customers feedback analysis

- Excellent service
- Very good customer support
- Very poor service
- Poor customer support
- Average service


## ---------------------------------------------------------

In [21]:
zip()
num = [1, 2, 3]
fruits = ['apple', 'mango', 'pineapple']
s = zip(num, fruits)
ss = tuple(s)
print(ss)
#print(type(num))

for n, fr in zip(num, fruits):
    print(n, ': ', fr)

((1, 'apple'), (2, 'mango'), (3, 'pineapple'))
1 :  apple
2 :  mango
3 :  pineapple


In [151]:
num, fruits = zip(*ss)

In [152]:
print(num)
print(fruits)

(1, 2, 3)
('apple', 'mango', 'pineapple')


## ---------------------------------------------------------

# CASE STUDY 3
#### Policy Data Transfer 

In [22]:
import numpy as np
import pandas as pd

In [23]:
# columns: Policy number, Premium amount(incoorect), Insured amount, Claims amount(incorrect)
policy_data = np.array([[101, 6000, 200000, 2000],
                        [102, 12000, 400000, 3000],
                        [103, 18000, 600000, 5000],
                        [104, 24000, 800000, 10000]])

In [30]:
col = ['Policy number', 'Premium amount', 'Insured amount', 'Claims amount']
print(policy_data)

[[   101   6000 200000   2000]
 [   102  12000 400000   3000]
 [   103  18000 600000   5000]
 [   104  24000 800000  10000]]


In [52]:
data1 = pd.DataFrame(policy_data, columns = col#for column name assignment
                      , index = (1, 2, 3, 4)# for rows name assignment
                    )
print(data1)

   Policy number  Premium amount  Insured amount  Claims amount
1            101            6000          200000           2000
2            102           12000          400000           3000
3            103           18000          600000           5000
4            104           24000          800000          10000


In [46]:
print('wrong policy data:')
print(policy_data)

wrong policy data:
[[   101   2000 200000   6000]
 [   102   3000 400000  12000]
 [   103   5000 600000  18000]
 [   104  10000 800000  24000]]


In [47]:
policy_data[ :, [1, 3]] = policy_data[ :, [3, 1]]

In [48]:
print('Corrected policy data: ')
print(policy_data)

Corrected policy data: 
[[   101   6000 200000   2000]
 [   102  12000 400000   3000]
 [   103  18000 600000   5000]
 [   104  24000 800000  10000]]


In [49]:
# Total Claim amount
total_am = np.sum(policy_data[:, 3])

In [50]:
print('Total claim amount: ', total_am)

Total claim amount:  20000
