### array : data structure in numpy

In [25]:
import numpy as np

In [4]:
# 1D array
arr1 = np.array([1, 2, 3])
print(arr1)
print(type(arr1))
print(type([1, 2, 3]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'list'>


In [26]:
import time
li = list(range(100000000))
arr = np.arange(100000000)
start = time.time()
sum(li)
print(time.time()-start)
start = time.time()
np.sum(arr)
print(time.time()-start)

3.9766156673431396
0.13552641868591309


In [5]:
# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [31]:
# array of zeros, ones and range

In [34]:
arr = np.zeros((2, 3)) # 2-rows and 3-columns
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
arrs1 = np.ones((2, 4))
print(arrs1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
ar = np.arange(2, 11, 2)
print(ar)

[ 2  4  6  8 10]


### Array Operations

In [48]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
print(a+b)
print(a**2)
print(a/b)

[3 6 9]
[1 4 9]
[0.5 0.5 0.5]


In [50]:
print(a+4)

[5 6 7]


In [27]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[1, 2, 3], [4, 5, 6]])
print(x+y)
print(x+10)
print(x*y)

[[ 2  4  6]
 [ 8 10 12]]
[[11 12 13]
 [14 15 16]]
[[ 1  4  9]
 [16 25 36]]


In [11]:
print(x[1, 1])

5


In [55]:
print(x[0, :])

[1 2 3]


In [14]:
print(x[ :, ])

[[1 2 3]
 [4 5 6]]


In [15]:
print(x[:, -1])

[3 6]


In [17]:
print(x)

[[1 2 3]
 [4 5 6]]


In [28]:
print(x[:,0])

[1 4]


### Reshaping
##### reshape(rows, columns): used to change the dimensions of an array in numpy

In [100]:
reshaped = np.arange(12).reshape(2, 6)
print(reshaped)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Functions of Numpy

In [42]:
arr = np.array([3, 1, 4, 8, 2, 9, 7])
print(f'Mean: {np.mean(arr)}')

Mean: 4.857142857142857


In [43]:
print(f'Standard Deviations: {round(np.std(arr), 2)}')

Standard Deviations: 2.9


In [44]:
print(np.median(arr))

4.0


In [45]:
print(np.sort(arr))

[1 2 3 4 7 8 9]


In [49]:
# linspace(start, stop, num):
# used to create array in numpy or generates sequence of evenly spaced-values
print(np.linspace(1, 2, 5))
# start: sequence starts value
# stop: sequence stop value and it is include in result
# num: specify samples means interval from 1 to 5 divides, how many parts

[1.   1.25 1.5  1.75 2.  ]


In [87]:
ran = np.random.randint(1, 4, (3, 3))

In [88]:
print(ran)

[[3 3 2]
 [1 3 2]
 [1 3 2]]


In [91]:
nd = np.arange(1, 26).reshape(5, 5)
print(nd)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [92]:
print(nd[1:4, 1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [93]:
print(nd[:, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [97]:
print('Row-wise sum: ', np.sum(nd, axis = 1))

Row-wise sum:  [ 15  40  65  90 115]


In [98]:
print('Column-wise sum: ', np.sum(nd, axis = 0))

Column-wise sum:  [55 60 65 70 75]


# CASE STUDY

In [104]:
claims = np.array([[10000, 12000, 15000], # for 1 holders
                  [3000, 9000, 20000],    # 2
                  [90000, 11000, 25000]]) # 3

In [105]:
print(f'Claims done by policy holder 3 in month 2: {claims[2, 1]}')

Claims done by policy holder 3 in month 2: 11000


In [106]:
print('Total claims per holders')
print(np.sum(claims, axis = 1))

Total claims per holders
[ 37000  32000 126000]


In [107]:
# avg claims per month

In [108]:
print('Avg claims per month', np.mean(claims, axis = 0))

Avg claims per month [34333.33333333 10666.66666667 20000.        ]


In [109]:
# claims above 15000
high_claims = claims[claims > 15000]
print(high_claims)

[20000 90000 25000]
